<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8" />
		<title><?php echo $title; ?></title>

		<link rel="stylesheet" type="text/css" href="<?php echo SITE_ROOT; ?>/css/reset.css" media="all" />
		<link rel="stylesheet" type="text/css" href="<?php echo $EddyFC[ 'skinfolder' ]; ?>/text.css" media="all" />
		<link rel="stylesheet" type="text/css" href="<?php echo $EddyFC[ 'skinfolder' ]; ?>/styles.css" media="all" />

		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script>
	</head>

	<body>
		<?php include_view(); ?>
	</body>
</html>