<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8" />
		<title><?php echo $title; ?></title>

		<link rel="stylesheet" href="<?php echo SITE_ROOT; ?>/css/reset.css" />
		<link rel="stylesheet" href="<?php echo SITE_ROOT; ?>/css/text.css" />

		<!-- <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script> -->
		<?php
			if ( is_array( $headjs ) ) {
				foreach ( $headjs as $src ) {
					echo '<script src="' . $src . '"></script>';
				}
			}
		?>
	</head>

	<body>
		<div style="width:800px;margin:auto">
			<?php EddyView::load(); ?>
		</div>
	</body>
</html>