<h1>Success!</h1>
<p>Give yourself a pat on the back, you got Eddy working! Now you can get it working for you.</p>
<p>Eddy is a simple framework with a simple purpose: to make building web apps in PHP easier.</p>
<p>
	A lot of frameworks focus on giving you everything you <i>might</i> need;
	Eddy, on the other hand, only provides what you really need - then gets out of the way.
</p>

<p>
	Based on RESTful principles, it makes building lean and beautiful apps easy while keeping your
	coding standards high. It's not strict MVC, but it encourages you to use it that way.
</p>

<p>It's got theming down to a fine art. AJAX and even building a basic API are a doddle!</p>

<?php EddyView::load_partial( 'dummy' ); ?>